module.exports = {
  CR21a: {
    learn: ['Sequence of Events', 'https://www.youtube.com/embed/ZEWitdYB6_Y?rel=0&amp;showinfo=0', 'https://www.youtube.com/embed/w33-m8-geuM?rel=0&amp;showinfo=0', 'Telling a story using the sequence of events means to tell the story in order. Remember to use words like "first","next", "then", "after that", and "finally".'],
    practice: ['Telling a story using the sequence of events means to tell the story in order. Remember to use words like "first","next", "then", "after that", and "finally".', 'Watch the video, then answer the questions.', 'What happened in the beginning of the story?', '(Remember to use either "first", "next", "then", "after that", or "finally" in your answer.)', 'https://www.youtube.com/embed/vbuq7w3ZDUQ?rel=0&amp;showinfo=0', 'What happened in the middle of the story?', '(Remember to use either "first", "next", "then", "after that", or "finally" in your answer.)', 'What happened at the end of the story?', '(Remember to use either "first", "next", "then", "after that", or "finally" in your answer.)'],
    books: [
      'https://lh3.googleusercontent.com/KaQ1UwagXzVLCtmZeSGv-TcuiFJoM441-DpIjXWvy32x0b4F1i-c_C9uyHOy5bVsfMdHiZyvSiWW8gvaAsZkSf_oo8vDsX3vI58XsAZuF0ZZO9NbWTA1tjIFcLuvrKCZUGCIrh-ppwH2rNKyxoH1ty6MavcgHSLcuonHF4txz0SG27BsldCJTuVCcWemz3XZwaZaqXUB4vce2IP7x_X3PaYSMV89qtGHDNskmEgagICQq0HWrycpbBNjYVUty8jcR1VOocDcK69d4lhx-puy3jco_ZsE3BrJe581LCtOzhxF7JxpJKxPZ-M8jhAHYy2e4H0eUL1dB5QFZ7JbY2SeFyeWMF8kjruAO3WJvkqjJOy_tD4fEE-aPsMorQiTUy5K-DduyaeB95iOF2n2DmbOBq3Q1sfGMsuOlbUOnn5-CffPAErARKHC3BJceW4SaPluADhI_ihtFW_E1JcP061k1J5BWtKFh3ylT89r5QZsI_SfMB1xzlXbrOy1_jxwHIu9UkCRz24Fu_LCacOsUXDtZSjGX3-J_gx_1109oGGvl7UVWJcsq3Bz8ZMtmhkeuTC0koR1lpir40_IaeUNzPXHfjstt2gAD1AjRC3oRaY=w183-h275-no', 'https://lh3.googleusercontent.com/yRFlNTGxb2c5dqePKdnRFhrkQhqi4pfPUwKgZ4XhT8Wt0sjhMwVAr7GPnYLiIBdELgl9eqz1XXjqVe0hfEiziS-uwJJK9SGrVf26MVEeETTJi4yEhXrEC1JhmdnPZAwPrmSytrcR-fqXKE3SaC97MtYUqdERoOS40K35T3NkQI0J5q3dfrPcFDmjP92jgWCzL59vCoOGmuUaJmJ02x3FW1Gaktou4cZpGOENoKZJAdKpNmwxkkfQ3SS9dvlRM0o8vrRaLBpoSvRFhHYTLCZ-QWeBYsVnk5Jirkm5vy81w9GX-buA8Tbtni9E72BzNOQgBL3YCBdAM5yop0fsqvBy1q00hcEXLDcFY43VIb1KA3UdVJf3cGa615soQ7O1-O6ulqqca_-HQ2d3UGvgG9T3jfN0Aq8r92PII4ob3n23Lwuea0tDP28ggHSnnRUUD623RG7k460_Nlheh6nprsNeF6SXy1BL6ZdISFeIfWxrTWUmJD5Q393PT1oXRN3hhYtMsY1ks_09wTobDAZThoeRZdgOisZROPF8aqKXal1X0t5C56gLrgbE72EtKnwwqKjPNyQ_v0zxtAzVcqNL80KusR2vJo07uPM6akN1OyM=s260-no', 'https://lh3.googleusercontent.com/4G8OcJvgSP4BqlofA80GXDqYvUHqgFjpcMYkA7hjlfCu48yqUjbX6xCSDZPa1siPcyg0Mxw7Jeic9SD1MPdOQxtwyzly860QkmFQ36m3xM2H6irKJ40to9b2-HXSPEDP8c6wEHzSaix44IRM4GvbZ4egjEQMe5eaJYfCvR6xTNr2-mrxZmBKFqVyi2BkO4VRE6DHiYkFsgHv-43B0sKCT8ZkkR9aG-Vm9uAorIHW3_fNNEqrlr9dt6UJHmyAlVW2-V-a96ZumtvmUx1YWenG16U49fBUZEMfqE0s9iBRpH-CYrjV05aJHgXrMVhnyVQcwgr5CRgoESkY38EE3HAM6bE4C3c2MjtQiTQxBFAkcYuOzUSq6m-lcdIsiDwUCQ4ZlS4VGCbBjeA2oS7Z4T4yYLtkOvvEQgG_KE5WzFvDMyamZSHDCwlvt4VtCz2kNWE5dKDMnIXVqo8d_7LbDy96JG3lQ8frhS7aR5D7cDJjekO1-fJgFUmy24dvFd11qFY5a0QnbFjoAgZ9xf23GkrODGxc1yg8BAU_DDCVrFAcjrSinja_fqOojWl5wxV5n5qNdawn_APiKyLNhx2ve2gS5a_Q_Afvvj4IXaxDMso=w376-h499-no', 'https://lh3.googleusercontent.com/XjVzt9DPuB_JvBH_sJ56oU-C3xTI55NYWFPWfS10NBvAxFI9x8qgeBTKbgJMBCuNGnEX_fyYFLJ8iLtBNv5WVf17oKkdBB0i_2Olyn9-Dkv1TYb2N_n7tfqaqsLPNziclEgLULf9pAbrveZ8FSxikbb8JkD_EaPFSA_O6v_aG28fJA8FwNWWb2ln4ULsZ1UkxX38mFOytdBVsiXUhmh_-DsZTmtltZBB2mtNNEJLRcpF97BpkExTArfJsVrfS5zg9lOIdadrydFkPWv6DW4ju2k9AxvOKm_JZfmY6fjhV4waFqqd08rH-ytCWHt2C8b90q5wngaEFkwT7nzfnsiegb1k-1KucRJbvXtCROFELdlrZ3UtY9VrUkkxU3mCWIMdC3uFXDJCsOptUw9ZeuwcO_qu8ox3ByBTi0JZOl_Qvhdqlb1ExMVM8a5_ETAQnGrFejFBdfcmE3Ia1eqollL8SklbXnqNchTikaoXQ620hUC-lUFoRBX5c1-23EwZMKKMKR7ZMt3zo1gl2R_AEgXF3ztcvnoq3YKPi31E0a9EYR-znKDqQlSGpIqz0l3mU589RbC1wsubkeiJvPpaXDvPFnjmtciA_3FzAgvmqxw=w500-h404-no'
    ],
    activity: ['Telling a story using the sequence of events means to tell the story in order. Remember to use words like "first","next", "then", "after that", and "finally".', 'Think about the sequence of events in the book you read. You only have four bubbles, so choose the most important events. Use each bubble to write about an event in order. Don\'t forget to use the words "first", "next", "then", "after that", and "finally" in your answers, and remember to use complete sentances!', 'Event #1', 'Event #2', 'Event #3', 'Event #4', '', ''],
    lessonComplete: ['Nice job! Keep up the good work!', 'https://giphy.com/embed/r2BtghAUTmpP2']
  },
  CR22a: {
    learn: ['Story Structure', 'https://www.youtube.com/embed/NxiiOXycvlI?rel=0&amp;showinfo=0&amp;start=7', 'https://www.youtube.com/embed/hqEqT7wG9zA?rel=0&amp;showinfo=0&amp;start=10', '1. Characters: Who is in the story \n 2. Setting: Where the story happens \n 3. Problem: Something in the story that needs to be fixed \n 4. Solution: How the problem gets fixed \n 5. Events: Things that happen in the story'],
    practice: ['1. Characters: Who is in the story \n 2. Setting: Where the story happens \n 3. Problem: Something in the story that needs to be fixed \n 4. Solution: How the problem gets fixed \n 5. Events: Things that happen in the story', 'Watch the video, then answer the questions.', 'Remember, a setting is where the story happens.', 'What is the setting of this story? How do you know?', 'https://www.youtube.com/embed/2GCzyZexnNE?rel=0&amp;showinfo=0', 'Remember, character are people of animals in the story.', 'Who are the characters in this story?', 'Remember, a problem is something that needs to be fixed.', 'What is the problem in this story?'],
    books: [
      'https://i.imgur.com/x5LhCS0.jpg', 'https://i.imgur.com/ZUPEJBx.jpg'],
    activity: ['1. Characters: Who is in the story \n 2. Setting: Where the story happens \n 3. Problem: Something in the story that needs to be fixed \n 4. Solution: How the problem gets fixed \n 5. Events: Things that happen in the story', 'Look back in the book and find the five differnt parts of story structure. In each bubble, fill in the part of story structure it asks for and two reasons why you think that. Remember to use complete sentances!', 'Characters', 'Setting', 'Problem', 'Solution', 'Reason #1', 'Reason #2'],
    lessonComplete: ['Be proud of yourself! You accomplished something great today!', 'https://giphy.com/embed/jbtCu5ScXS2He']
  },
  CR23a: {
    learn: ['Character\'s Response to Events', 'https://giphy.com/embed/3oEhmKV4lJzCspvw9W', 'https://www.youtube.com/embed/Iekv6R9U1dM?rel=0&amp;showinfo=0', 'A character\'s response is how a character feels or what they do when something happens in the story.'],
    practice: ['A character\'s response is how a character feels or what they do when something happens in the story.', 'Watch the video, then answer the questions.', 'How does the first bird respond when they other birds land near it?', 'How do you know?', 'https://www.youtube.com/embed/MZ2tq0F8-ww?rel=0&amp;showinfo=0', 'How do the small birds respond when they see the large bird?', 'How do you know?', 'How do the small birds respond when the big bird flips upside down?', 'How do you know?'],
    books: [
      'https://i.imgur.com/9Z1DiQE.jpg', 'https://i.imgur.com/EdC1wTz.jpg', 'https://i.imgur.com/KcLlCzs.jpg'],
    activity: ['A character\'s response is how a character feels or what they do when something happens in the story.', 'Look back in the book and find some events and character\'s responses to them in the story. In each bubble, write about a major event and how characters responded to it. Remember to use complete sentances!', 'Event #1', 'Event #2', 'Event #3', 'Event #4', 'Response #1', 'Response #2'],
    lessonComplete: ['Keep growing your brain and trying things even if they\'re hard!', 'https://giphy.com/embed/3oEdvaBf2nJbIKrWOQ']
  },

  CR24a: {
    learn: ['Main Topic in an Informational Text', 'https://www.youtube.com/embed/-o_lA7oSSWs?rel=0&amp;showinfo=0&amp;start=8', 'https://www.youtube.com/embed/C1W46goOpu0?rel=0&amp;showinfo=0', 'An informational text is one that teaches us true things and a main topic is what the text is all about.'],
    practice: ['An informational text is one that teaches us true things and a main topic is what the text is all about.', 'Watch the video, then answer the questions.', 'Is this video informational?', 'How do you know?', 'https://www.youtube.com/embed/3pi6acgWOdk?rel=0&amp;showinfo=0', 'What do you think is the main topic of this video?', '', 'What is one piece of information that tells you that is the main topic?', ''],
    books: [
      'https://i.imgur.com/kaqqHhy.jpg'],
    activity: ['An informational text is one that teaches us true things and a main topic is what the text is all about.', 'In the first bubble, write what the main topic of the book was. In the next three bubbles, write about pieces of information you learned about that main topic. Remember to use complete sentances!', 'Main Topic', 'Information', 'Information', 'Information', '', ''],
    lessonComplete: ['You can learn ANYTHING you want if you work hard enough. Great job today!', 'https://giphy.com/embed/l378hTnSHp8EI0la0']
  },
  CR25a: {
    learn: ['Informational Text Features', 'https://www.youtube.com/embed/3mAl9QMJJTo?rel=0&amp;showinfo=0', 'https://giphy.com/embed/l44Q9EPJIzYediXp6', 'Important informational text features are headings (the title of a chapter or section), captions (text near the picture that tells you more about the picture), and pictures.'],
    practice: ['Important informational text features are headings (the title of a chapter or section), captions (text near the picture that tells you more about the picture), and pictures.', 'Read the article about Hourglass Dolphins, then answer the questions.', 'What is the heading of this article?', 'How do you know?', 'https://lh3.googleusercontent.com/E25-UQ9Wm7HEoFu9zE8Y5dJKxzIAF0Ve-2-YtU5a9ie911V4n_1R8NBWnceIHaHkK54RGJo9480PK9CsEpooHoRlWo6eD1pmuQibgHJJF9nDl8C6G2jlRdNLhI3rYXazkU0DPY2GX86vnwjC5gHz0RwCZssDoEB8qckeukSzudJKlNyrJjT2FQSrFCpWy8-xQT_8_zKcglzxBzSQdWAzGMh1Tsvyj7NjebGFSXGyitWauywMwzjFHInFeqGKGM-T4fJ6hNWMkyrb4ru9URV0eJt4rm0jaDF_xaJXtWfvBmw-GuBdAn-sbqgDTgPR4z9xCX-gM83084QFHwjp8HmtiyywDsMoelwcmdvQWjaJbHzUHo7VPUOV6ifl4Ug-R1L9y_vNGLTXQK-QSD8avbeC823E1V_gEi8rSBvuMD2iJXMoTV2vRDEyBUbDOM9k-kScGlQNGSsYKVWNRHFHfOeu81W_buPk0KUkwEpULUeMy5zg3d1K3l7kBGpaRy_0nqvDRqcz1i29zJE3VfnQKFgwBOphDk-YdOYTy732myt9ibI2yF0tEm1QCnUjL4DLCcEXHLG8lwjJpMJflGCyeT8E1JyJjLwED5vXuwrLuDw=w882-h492-no', 'What does the caption tell you?', 'How did you know that was the caption?', 'What is one piece of information you learned just by looking at the picture?', ''],
    books: [
      'https://lh3.googleusercontent.com/0xxx2p1ekR69xvlUG018_-8ggME3YPeeBewRw59cMh3veh7v6xk8f_oNewR4OFZmRfTsTXlBLED8we3CTjQpTqo0LM3X0LtJvbIwq8vHY0DJxDoQIw67ImlLujY9aleIHcPoWszK8yx9ml9ufWeHKCdfoajelYgj2_6BAIqwELTBrPGcfC5KDKa10VzOicZyzJXCq7fp9gRZvHHHJWVqW9m9tVNkUkHQnr_5Xp76-ew6EdKdS7792LRrM9lkF8PsFY7m0QqPS-dQFw8PKr0l9tXnPeidDkoaiMoBmQFULYScgLjYoIKsQWK4F9laJrn9QlN-y2oQKaPAICprM59kIF1OBNjRorrdMSxSp2s_xkMoYZjrkTBBoMiYbMaVyX8bGNd_5p9BiFPnr8mDmoWZ8riwu1ejR-vBNRQDVeJ5fZea6AoCrAFrIqQqQPvFLpE793CRowO0ZW78YLOCLWHCtFJFjfVnhAB9uEgwYK86wt1fM0AkvC6PPTV-bSW-8z58MU2lvr2XyZZXjcpdYmVNNFEyfJBrbb1tDtn8QPajBY4_3XvBYbkChTT39W5k8aVGwgTBrUTko4ep8DMkaxK0r4bNibQNEdmlxSheSUk=w702-h723-no'],
    activity: ['Important informational text features are headings (the title of a chapter or section), captions (text near the picture that tells you more about the picture), and pictures.', 'Choose one section from the book you read. Use the bubbles to fill in information about the informational text features in that section. Remember to use complete sentances!', 'What is the heading?', 'What does a caption in this section tell you?', 'What is something you learned just by looking at one of the pictures?', 'What is one cool fact you learned?', 'How do you know?', ''],
    lessonComplete: ['Follow your dreams and put in the work to become who you want to be!', 'https://giphy.com/embed/3o7aDerSmoHSvdLrFK']
  },
  CR26a: {
    learn: ['Informational Text Features', 'https://www.youtube.com/embed/3mAl9QMJJTo?rel=0&amp;showinfo=0', 'https://giphy.com/embed/l44Q9EPJIzYediXp6', 'Important informational text features are headings (the title of a chapter or section), captions (text near the picture that tells you more about the picture), and pictures.'],
    practice: ['Important informational text features are headings (the title of a chapter or section), captions (text near the picture that tells you more about the picture), and pictures.', 'Read the article about Hourglass Dolphins, then answer the questions.', 'What is the heading of this article?', 'How do you know?', 'https://lh3.googleusercontent.com/E25-UQ9Wm7HEoFu9zE8Y5dJKxzIAF0Ve-2-YtU5a9ie911V4n_1R8NBWnceIHaHkK54RGJo9480PK9CsEpooHoRlWo6eD1pmuQibgHJJF9nDl8C6G2jlRdNLhI3rYXazkU0DPY2GX86vnwjC5gHz0RwCZssDoEB8qckeukSzudJKlNyrJjT2FQSrFCpWy8-xQT_8_zKcglzxBzSQdWAzGMh1Tsvyj7NjebGFSXGyitWauywMwzjFHInFeqGKGM-T4fJ6hNWMkyrb4ru9URV0eJt4rm0jaDF_xaJXtWfvBmw-GuBdAn-sbqgDTgPR4z9xCX-gM83084QFHwjp8HmtiyywDsMoelwcmdvQWjaJbHzUHo7VPUOV6ifl4Ug-R1L9y_vNGLTXQK-QSD8avbeC823E1V_gEi8rSBvuMD2iJXMoTV2vRDEyBUbDOM9k-kScGlQNGSsYKVWNRHFHfOeu81W_buPk0KUkwEpULUeMy5zg3d1K3l7kBGpaRy_0nqvDRqcz1i29zJE3VfnQKFgwBOphDk-YdOYTy732myt9ibI2yF0tEm1QCnUjL4DLCcEXHLG8lwjJpMJflGCyeT8E1JyJjLwED5vXuwrLuDw=w882-h492-no', 'What does the caption tell you?', 'How did you know that was the caption?', 'What is one piece of information you learned just by looking at the picture?', ''],
    books: [
      'https://lh3.googleusercontent.com/0xxx2p1ekR69xvlUG018_-8ggME3YPeeBewRw59cMh3veh7v6xk8f_oNewR4OFZmRfTsTXlBLED8we3CTjQpTqo0LM3X0LtJvbIwq8vHY0DJxDoQIw67ImlLujY9aleIHcPoWszK8yx9ml9ufWeHKCdfoajelYgj2_6BAIqwELTBrPGcfC5KDKa10VzOicZyzJXCq7fp9gRZvHHHJWVqW9m9tVNkUkHQnr_5Xp76-ew6EdKdS7792LRrM9lkF8PsFY7m0QqPS-dQFw8PKr0l9tXnPeidDkoaiMoBmQFULYScgLjYoIKsQWK4F9laJrn9QlN-y2oQKaPAICprM59kIF1OBNjRorrdMSxSp2s_xkMoYZjrkTBBoMiYbMaVyX8bGNd_5p9BiFPnr8mDmoWZ8riwu1ejR-vBNRQDVeJ5fZea6AoCrAFrIqQqQPvFLpE793CRowO0ZW78YLOCLWHCtFJFjfVnhAB9uEgwYK86wt1fM0AkvC6PPTV-bSW-8z58MU2lvr2XyZZXjcpdYmVNNFEyfJBrbb1tDtn8QPajBY4_3XvBYbkChTT39W5k8aVGwgTBrUTko4ep8DMkaxK0r4bNibQNEdmlxSheSUk=w702-h723-no'],
    activity: ['Important informational text features are headings (the title of a chapter or section), captions (text near the picture that tells you more about the picture), and pictures.', 'Choose one section from the book you read. Use the bubbles to fill in information about the informational text features in that section. Remember to use complete sentances!', 'What is the heading?', 'What does a caption in this section tell you?', 'What is something you learned just by looking at one of the pictures?', 'What is one cool fact you learned?', 'How do you know?', ''],
    lessonComplete: ['Follow your dreams and put in the work to become who you want to be!', 'https://giphy.com/embed/3o7aDerSmoHSvdLrFK']
  },
  CR27a: {
    learn: ['Making Inferences', 'https://www.youtube.com/embed/to30AJm2epQ?rel=0&amp;showinfo=0', 'https://www.youtube.com/embed/rCmTlK_rb0U?rel=0&amp;showinfo=0', 'An inference is a something you figure out using the clues in the words and pictures.'],
    practice: ['An inference is a something you figure out using the clues in the words and pictures.', 'Read the text in each box and then answer the questions that follow.', '1. Juan opened the door to his house. All his friends were there! There was also a cake, present, and balloons.', 'What inference can we make about what is happening in Juan\'s house?', 'https://giphy.com/embed/PsFhnunpPizlu', '2. Even though Tiana put on her hat and her scarf, she was still shivering.', 'What inference can we make about how Tiana is feeling?', '3. Bryan got an A on a difficult math test. He smiled all the way home.', 'What inference can you make about how Bryan is feeling?'],
    books: [
      'https://i.imgur.com/x5LhCS0.jpg', 'https://i.imgur.com/ZUPEJBx.jpg', 'https://i.imgur.com/Kx3oeLd.jpg'
    ],
    activity: ['An inference is a something you figure out using the clues in the words and pictures.', 'Look back in the book and find four places where you can make inferences. In each bubble, write one inference and then two clues that helped you make that inference. Remember to use complete sentances!', 'Inference', 'Inference', 'Inference', 'Inference', 'Clue #1', 'Clue#2'],
    lessonComplete: ['You did it! Keep working hard!', 'https://giphy.com/embed/l0MYu0z6TH0t4PFII']
  }
}
